<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>control-panel.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="control-panel.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\Antenna Rotator.html" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SerialConnect\SerialConnect.csproj" />
    <ProjectReference Include="..\SerialMonitor\SerialMonitor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GMap.NET.WinForms" Version="2.1.7" />
    <PackageReference Include="Mapsui.Rendering.Skia" Version="5.0.2" />
    <PackageReference Include="ProjNET" Version="2.1.0" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

</Project>